In [19]:
import numpy as np

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [22]:
np.ones([2,2], int)

array([[1, 1],
       [1, 1]])

In [23]:
np.ones([3,2], float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
X = np.array([[1,2,3], [4,5,6]], int)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
np.full((4, 4), 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.random.randint(10, size=3)

array([0, 3, 5])

In [28]:
X = [1, 2, 3]
Y = np.array(X)
print(Y)

[1 2 3]


In [29]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
X = np.array(['A','B','C','D','E'])

X[-1]

'E'

In [31]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

In [32]:
X = [0, 10, -5, 40, -3]

X.sort()
print(X)

[-5, -3, 0, 10, 40]


In [33]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

bruh = X > 5

print(X[bruh])

[ 6 10]


In [34]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

print(X.sum())
print(X.mean())
print(X.std())
print(X.max())

43
4.777777777777778
2.096440251568134
9
